using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using System.IO;


namespace Jmx.Monogame.ScreenTools
{
    public class ScreenShotHelper
    {
        GraphicsDevice _graphicsDevice;
        public ScreenShotHelper(GraphicsDevice graphicsDevice)
        {
            _graphicsDevice = graphicsDevice;
        }

        /// <summary>
        /// Generate and save a screenshot of the entire backbuffer
        /// </summary>
        /// <param name="filename">Filename of the screenshot (autogenerated with timestamp if not specified)</param>
        public void SaveScreenshot(string filename = "")
        {
            Color[] colors = new Color[_graphicsDevice.Viewport.Width * _graphicsDevice.Viewport.Height];

            _graphicsDevice.GetBackBufferData<Color>(colors);

            using (Texture2D tex2D = new Texture2D(_graphicsDevice, _graphicsDevice.Viewport.Width, _graphicsDevice.Viewport.Height))
            {

                tex2D.SetData<Color>(colors);
                if (string.IsNullOrEmpty(filename))
                {
                    filename = $"screenshot_{DateTime.Now.ToFileTime()}.png";
                }
                using (FileStream stream = File.Create(filename))
                {
                    tex2D.SaveAsPng(stream, _graphicsDevice.Viewport.Width, _graphicsDevice.Viewport.Height);                    
                }                                
            }            
        }

    }




}
